cacheFolder: ./.yarn/cache

checksumBehavior: throw

compressionLevel: mixed

defaultLanguageName: node

defaultProtocol: "npm:"

defaultSemverRangePrefix: ^

enableGlobalCache: false

enableStrictSsl: true

enableTelemetry: false

httpRetry: 3

httpTimeout: 60000

networkConcurrency: 8

nmHoistingLimits: none

nodeLinker: node-modules

preferInteractive: true

yarnPath: .yarn/releases/yarn-4.1.0.cjs
