const PRINT_WIDTH = 80;

module.exports = {
  env: {
    es6: true,
  },
  extends: [
    'eslint:recommended',
    'plugin:promise/recommended',
    'plugin:import/errors',
    'plugin:import/warnings',
    'plugin:import/typescript',
    'plugin:@typescript-eslint/recommended',
    'plugin:prettier/recommended',
    'plugin:@typescript-eslint/recommended-requiring-type-checking',
  ],
  ignorePatterns: [
    '.eslintrc.*',
    '**/node_modules',
    '**/build',
    '**/dist',
    '**/logs',
  ],
  overrides: [
    {
      files: ['*'],
      rules: {
        '@typescript-eslint/ban-types': 'off',
        '@typescript-eslint/camelcase': 'off',
        '@typescript-eslint/explicit-member-accessibility': 'off',
        '@typescript-eslint/indent': [0, 2],
        // TODO: eslint v3 `https://github.com/typescript-eslint/typescript-eslint/releases/tag/v3.0.0`
        '@typescript-eslint/naming-convention': [
          'error',
          // {
          //   format: ['camelCase'],
          //   selector: 'default',
          // },
          // {
          //   custom: {
          //     // TODO: Match `allowVariables` regex.
          //     match: true,
          //     regex: allowVariables.join('|'),
          //   },
          //   format: ['camelCase', 'snake_case'],
          //   selector: 'variable',
          // },
          {
            format: ['camelCase', 'UPPER_CASE', 'snake_case', 'PascalCase'],
            leadingUnderscore: 'allow',
            selector: 'variable',
            trailingUnderscore: 'allow',
          },
          {
            format: ['camelCase', 'snake_case'],
            selector: 'parameter',
          },
          {
            format: ['PascalCase'],
            selector: 'typeLike',
          },
          {
            format: ['PascalCase'],
            selector: 'typeParameter',
            suffix: ['T'],
          },
          // {
          //   format: ['PascalCase'],
          //   prefix: [
          //     'allow',
          //     'can',
          //     'did',
          //     'disable',
          //     'enable',
          //     'has',
          //     'in',
          //     'is',
          //     'should',
          //     'will',
          //     'with',
          //     'visible',
          //   ],
          //   selector: 'variable',
          //   types: ['boolean'],
          // },
          {
            format: ['PascalCase'],
            selector: 'class',
          },
          {
            format: ['PascalCase', 'camelCase'],
            leadingUnderscore: 'allow',
            selector: 'function',
          },
        ],
        '@typescript-eslint/no-empty-interface': 'off',
        '@typescript-eslint/no-explicit-any': 'off',
        '@typescript-eslint/no-floating-promises': [
          'warn',
          { ignoreVoid: true },
        ],
        /** Use array destructuring [index, data] Object.entries(obj) instead. */
        '@typescript-eslint/no-for-in-array': 'error',
        '@typescript-eslint/no-inferrable-types': 'warn',
        '@typescript-eslint/no-misused-promises': [
          'error',
          {
            checksVoidReturn: false,
          },
        ],
        '@typescript-eslint/no-unsafe-assignment': 'off',
        '@typescript-eslint/no-unsafe-call': 'off',
        '@typescript-eslint/no-unsafe-member-access': 'off',
        '@typescript-eslint/no-unsafe-return': 'off',
        '@typescript-eslint/no-unused-vars': 'warn',
        '@typescript-eslint/no-useless-constructor': 'error',
        '@typescript-eslint/no-var-requires': 'warn',
        '@typescript-eslint/prefer-nullish-coalescing': 'off',
        '@typescript-eslint/prefer-optional-chain': 'warn',
        '@typescript-eslint/restrict-template-expressions': 'off',
        '@typescript-eslint/unbound-method': 'off',
        'arrow-parens': ['warn', 'always'],
        camelcase: 'off',
        'import/named': 'off',
        'import/namespace': 'off',
        'import/no-unresolved': 'off',
        'no-void': ['warn', { allowAsStatement: true }],
        'prettier/prettier': [
          'warn',
          {
            arrowParens: 'always',
            bracketSpacing: true,
            endOfLine: 'auto',
            insertPragma: false,
            printWidth: PRINT_WIDTH,
            proseWrap: 'preserve',
            requirePragma: false,
            semi: true,
            singleQuote: true,
            tabWidth: 2,
            trailingComma: 'es5',
          },
        ],
        quotes: [
          'warn',
          'single',
          { allowTemplateLiterals: false, avoidEscape: true },
        ],
        'react-hooks/exhaustive-deps': 'off',
      },
    },
  ],
  parser: '@typescript-eslint/parser',
  parserOptions: {
    ecmaFeatures: {
      arrowFunctions: true,
      blockBindings: true,
      classes: true,
      defaultParams: true,
      destructuring: true,
      forOf: true,
      generators: true,
      jsx: false,
      module: true,
      objectLiteralComputedProperties: true,
      objectLiteralDuplicateProperties: true,
      objectLiteralShorthandMethods: true,
      objectLiteralShorthandProperties: true,
      regexUFlag: true,
      regexYFlag: true,
      restParams: true,
      spread: true,
      superInFunctions: true,
      templateStrings: true,
      unicodeCodePointEscapes: true,
    },
    ecmaVersion: 2021,
    extensions: ['.ts', '.tsx', 'js', '.jsx', '.html'],
    project: './tsconfig.json',
    sourceType: 'module',
  },
  plugins: [
    '@typescript-eslint',
    'eslint-plugin-tsdoc',
    'simple-import-sort',
    'import',
  ],
  rules: {
    curly: ['error', 'all'],
    'dot-notation': 'off',
    'lines-around-comment': [
      'off',
      {
        afterBlockComment: true,
        afterLineComment: false,
        allowArrayEnd: true,
        allowArrayStart: true,
        allowBlockEnd: true,
        allowBlockStart: true,
        allowObjectEnd: true,
        allowObjectStart: true,
        beforeBlockComment: true,
        beforeLineComment: false,
      },
    ],
    'max-len': [
      'warn',
      {
        code: PRINT_WIDTH,
        ignorePattern: '^s*import|export*',
        ignoreUrls: true,
      },
    ],
    'no-async-promise-executor': 'off',
    'no-case-declarations': 'off',
    'no-catch-shadow': 'warn',
    'no-console': 'warn',
    'no-mixed-operators': 'error',
    'no-multiple-empty-lines': ['warn', { max: 1 }],
    'no-prototype-builtins': 'off',
    'prefer-const': 'warn',
    'require-atomic-updates': 'off',
    'require-await': 'warn',
    'sort-imports': 'off',
    'import/first': 'error',
    'import/newline-after-import': 'off',
    'import/no-duplicates': 'error',
    'simple-import-sort/exports': 'warn',
    'simple-import-sort/imports': 'warn',
    'sort-keys': [
      'warn',
      'asc',
      {
        caseSensitive: true,
        natural: false,
      },
    ],
    'sort-vars': [
      'warn',
      {
        ignoreCase: false,
      },
    ],
    'tsdoc/syntax': 'warn',
  },
  settings: {
    'import/parsers': {
      '@typescript-eslint/parser': ['.ts', '.tsx'],
    },
    'import/resolver': {
      node: {
        extensions: ['.js', 'jsx'],
      },
    },
  },
};
